version: '3.3'

services:

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: ${PROJECT_NAME}-postgres:${PROJECT_VERSION}
    restart: unless-stopped
    build:
      context: services/postgres
      dockerfile: Dockerfile
    networks:
      - internal

  api:
    container_name: ${PROJECT_NAME}-api
    image: ${PROJECT_NAME}-api:${PROJECT_VERSION}
    restart: unless-stopped
    build:
      context: services/api
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - postgres

  web:
    container_name: ${PROJECT_NAME}-web
    image: ${PROJECT_NAME}-web:${PROJECT_VERSION}
    restart: unless-stopped
    build:
      context: services/web
      dockerfile: Dockerfile
    networks:
      - internal
    depends_on:
      - api

  webserver:
    container_name: ${PROJECT_NAME}-webserver
    image: ${PROJECT_NAME}-webserver:${PROJECT_VERSION}
    restart: unless-stopped
    build:
      context: services/webserver
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - internal
      - web
    depends_on:
      - web

networks:
  internal:
  web:
    external: true