version: '3.3'

services:

  postgres:
    image: ${PROJECT_NAME}-postgres:development
    restart: "no"
    env_file:
      - services/postgres/.env
    ports:
      - "5432:5432"

  api:
    image: ${PROJECT_NAME}-api:development
    restart: "no"
    env_file:
      - services/api/.env
    depends_on:
      - postgres

  web:
    image: ${PROJECT_NAME}-web:development
    restart: "no"

  webserver:
    image: ${PROJECT_NAME}-webserver:development
    restart: "no"
    ports:
      - "8000:80"

networks:
  internal:
  web:
    external: true