version: '3.3'

services:

  postgres:
    image: ${PROJECT_NAME}-postgres:development
    restart: "no"
    env_file:
      - services/postgres/.env
    volumes:
    - data-postgress:/var/lib/postgresql/data
    networks:
      - internal

  testing:
    container_name: ${PROJECT_NAME}-postgres-testing
    image: ${PROJECT_NAME}-postgres:development
    restart: "no"
    build:
      context: services/postgres
      dockerfile: Dockerfile
    env_file:
      - services/postgres/.env.testing
    volumes:
      - data-testing:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal

  api:
    image: ${PROJECT_NAME}-api:development
    restart: "no"
    env_file:
      - services/api/.env
    command: ["npm", "run", "watch"]
    volumes:
      - ./services/api/src:/app/src
      - ./services/api/tsconfig.json:/app/tsconfig.json
      - ./services/api/tslint.json:/app/tslint.json
      - ./services/api/package.json:/app/package.json
      - ./services/api/package-lock.json:/app/package-lock.json
      - ./services/api/node_modules:/app/node_modules
      - ./services/api/jest.config.js:/app/jest.config.js
      - ./services/api/.env.dist:/app/.env
    depends_on:
      - postgres
      - testing

  admin:
    image: ${PROJECT_NAME}-admin:development
    restart: "no"
    env_file:
      - services/admin/.env
    volumes:
      - ./services/admin/client:/app/client
    networks:
      - internal

  webserver:
    image: ${PROJECT_NAME}-webserver:development
    restart: "no"
    ports:
      - "8000:80"

volumes:
  data-postgress:
    driver: local
  data-testing:
    driver: local

networks:
  internal:
  web:
    external: true